import {
  IMAGE_MEDIA_DESKTOP_WIDTH,
  IMAGE_MEDIA_MOBILE_WIDTH,
  IMAGES_CDN,
  CONTACT_EMAIL,
  SERVICES_GATEWAY_URL
} from "./config";

import { SERVICES_API_KEY } from "./secrets";

export {
  IMAGE_MEDIA_DESKTOP_WIDTH,
  IMAGE_MEDIA_MOBILE_WIDTH,
  IMAGES_CDN,
  CONTACT_EMAIL,
  SERVICES_GATEWAY_URL,
  SERVICES_API_KEY
};
