import {
  APPLICATON_PDF_FILENAME,
  APPLICATION_ONLINE_URL,
  CDN_URL,
  CLIENT_NAME,
  CONTACT_ADDRESS,
  CONTACT_PHONE_NUMBER,
  GOOGLE_MAPS_LOCATION,
  HR_CONTACT_EMAIL,
  MARKETING_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL
} from "./config";

export {
  APPLICATON_PDF_FILENAME,
  APPLICATION_ONLINE_URL,
  CDN_URL,
  CLIENT_NAME,
  CONTACT_ADDRESS,
  CONTACT_PHONE_NUMBER,
  GOOGLE_MAPS_LOCATION,
  HR_CONTACT_EMAIL,
  MARKETING_CONTACT_EMAIL,
  SERVICES_GATEWAY_URL
};
